### ISSUE TITLE
Jumpstart deploy vFXT cluster example not working - Last step

### ISSUE THREAD

**Issue by dedreira** [Azure/Avere#126]
Hi, I'm trying to configure an Avere vFXT cluster to mount it into an Azure Batch pool, and I'm following this quickstart tutorial:

https://github.com/Azure/Avere/blob/master/docs/jumpstart_deploy.md

But when I SSH to the controller node ,modify the deployment template and try to run the template in the controller node (the last step of the page) I get this error:

Traceback (most recent call last):
  File "/usr/local/bin/vfxt.py", line 4, in <module>
    __import__('pkg_resources').run_script('vFXT==0.5.0.2', 'vfxt.py')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3088, in <module>
    @_call_aside
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3072, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3101, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 576, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 589, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 778, in resolve
    raise DistributionNotFound(req, requirers)
**pkg_resources.DistributionNotFound: The 'secretstorage<3; (sys_platform == "linux2" or sys_platform == "linux") and python_version < "3.5"' distribution was not found and is required by keyring**

It seems that there's something that's not installed in the controller node (I also had to install enum34 package via pip because on a previous step I got this error:

Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/azure/cli/__main__.py", line 9, in <module>
    from knack.completion import ARGCOMPLETE_ENV_NAME
  File "/usr/local/lib/python2.7/dist-packages/knack/__init__.py", line 6, in <module>
    from .cli import CLI
  File "/usr/local/lib/python2.7/dist-packages/knack/cli.py", line 10, in <module>
    from .invocation import CommandInvoker
  File "/usr/local/lib/python2.7/dist-packages/knack/invocation.py", line 10, in <module>
    from .util import CLIError, CtxTypeError, CommandResultItem, todict
  File "/usr/local/lib/python2.7/dist-packages/knack/util.py", line 9, in <module>
    from enum import Enum
ImportError: No module named enum

tying to execute command "az login" inside the controller node.

I'm using Azure Cloud Shell.

I googled the error but I didn't find anything useful

Can you check it please?

Thanks!!

**Comment by dedreira** [comment]
Ok, I figured out, I had to install this package on the controller node:

https://pypi.org/project/SecretStorage/


Regards!
